- repo: local
  hooks:
    - id: pytest
      name: Run Pytest
      entry: pytest
      language: system
      stages: [pre-push]
      types: [python]
      files: ^project2/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        files: ^project2/
      - id: trailing-whitespace
        files: ^project2/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^project2/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
      - id: isort
        files: ^project2/

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: ^project2/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^project2/
