# Run specific hooks before committing changes
repos:
  # Black: auto-formats Python code
  - repo: https://github.com/psf/black
    rev: 25.1.0  # specific version of black
    hooks:
      - id: black
        files: ^project2/  # restrict to files in project2/
        stages: [pre-commit]

  # isort: sorts Python imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        files: ^project2/
        stages: [pre-commit]

  # mypy: static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^project2/
        stages: [pre-commit]

  # Miscellaneous useful pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files  # Warn if large files are staged for commit (prevents committing binaries or data dumps)
        files: ^project2/
      - id: check-merge-conflict  # Detect unresolved Git conflict markers like <<<<<<<, =======, >>>>>>>
        files: ^project2/
      - id: check-yaml  # Ensure all .yaml/.yml files are valid and parseable
        files: ^project2/
      - id: check-ast  # Ensure Python files are syntactically valid (AST parseable)
        files: ^project2/
      - id: check-case-conflict  # Prevent files with the same name but different cases (important for case-insensitive filesystems)
        files: ^project2/
      - id: trailing-whitespace  # Remove any trailing whitespace at the end of lines (enforces clean diffs)
        files: ^project2/
      - id: end-of-file-fixer  # Ensure each file ends with exactly one newline (common POSIX convention)
        files: ^project2/
      - id: debug-statements  # Prevent accidental use of `print()` or `pdb.set_trace()` in committed code
        files: ^project2/

  # Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        files: ^project2/
        stages: [pre-push]
  
  # run pytest
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest  # run tests before pushing
        entry: pytest
        language: system  # use system-installed pytest
        stages: [pre-commit]
        types: [python]
        files: ^project2/

# Run specific hooks before pushing changes
  # flake8: enforces Python PEP style rules:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: ^project2/
        stages: [pre-push]

  # mypy (again): ensure static typing checks before pushing, trying enforce type-hints 
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^project2/
        stages: [pre-push]
